# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4e50608dc061664c7c801071aa0a941af3caa33dee78c865b6832ade21b0c5bd4ed95a715e670dd3e29a793fbad3ac530acf55049b4e7d424dda931ce97068

test:
  secret_key_base: a5555db9a5eb0fbd445580a66802ad9e959389876e5730fc60d2708e3f94fe45d2806ea480b0428d7008882896457ce302e0d2298559f9f3fb5f629b7df55e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
